### PR TITLE
updated README to explain how to load certificates for Gitlab auth into SonarQube

### PR DESCRIPTION
**Pull request by OlivierDupre**

### CODE REVIEW

**Comment by gabrie-allaigre** [comment]
Hi, Thanks,
The certificate should only be added if it is not recognized by an authority.

**Comment by zemzela** [comment]
Thank you, i could not get the plugin to work until this.

**Comment by OlivierDupre** [comment]
@gabrie-allaigre that's right. Forgot to note that.

**Comment by gabrie-allaigre** [comment]
I integrated the text into the readme directly.
thank you

**Pull request closed without merging**
